name: Terminus - Update Homebrew
on:
  release:
    types: [published]
jobs:
  package_macos:
    runs-on: macos-latest
    name: Package a Homebrew release
    if: ${{ startsWith(github.ref, 'refs/tags/')  && github.repository == 'pantheon-systems/pantheon-cli' }}
    steps:
      - name: Bump Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          tap: pantheon-systems/external
          formula: t3
